name: Update Toolchains

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Sunday at midnight UTC (0 = Sunday, 6 = Saturday)

permissions:
  contents: write
  pull-requests: write

jobs:
  update-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rust-bitcoin/rust-bitcoin-maintainer-tools/.github/actions/update-stable@master
        with:
          token: ${{ secrets.RBMT_PRS }}
